name: Build Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  DOCKER_BUILDKIT_INLINE_CACHE: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Log in to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: docker buildx build --push --tag docker.io/bigjra/oifey-bot:latest .